# Generated by Django 5.1.3 on 2024-12-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="Shop",
        ),
    ]
